version: '3'
services:
  reverse-proxy:
    image: benlue/reverse-proxy:latest
    build:
      context: reverse-proxy
      dockerfile: Dockerfile
    networks:
      - swarm-network
    ports:
      - 80:80
      - 443:443

  s3root-ovh:
    image: s3root-ovh
    build:
      context: s3root-ovh
      dockerfile: Dockerfile
    networks:
      - swarm-network

  benlue-ovh:
    image: benlue-ovh
    build:
      context: benlue-ovh
      dockerfile: Dockerfile
    networks:
      - swarm-network

networks:
  swarm-network:
    external: true
